name: Publish

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0 

      - name: GitVersion Setup
        uses: gittools/actions/gitversion/setup@v1.1.1
        with:
          versionSpec: '5.x'
      
      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v1.1.1
        id: version
        with:
          useConfigFile: true
          configFilePath: GitVersion.yml
      
      - name: Use the version
        run: |
          echo ${{ env.semVer }}

      - name: Restore
        run: dotnet restore -r win-x64
      
      - name: Build
        run: dotnet build -r win-x64 --configuration Release --no-restore
      
      - name: Publish
        run: dotnet publish -r win-x64 --configuration Release --no-build -p:Version=${{ env.semVer }} /p:SelfContained=true /p:PublishSingleFile=true /p:PublishReadyToRun=true

      - name: Run
        run: ls ${{ github.workspace }}/bin/Release/net8.0/publish